cf:
  apiHost: "api.sys.tp.penso.io"  # Replace with your actual CF API endpoint
  username: "your-username"       # Replace with your CF username
  password: "your-password"       # Replace with your CF password
  organization: "tanzu-platform-demo"  # Matches CLI target
  space: "mcp-server"            # Matches CLI target

logging:
  level:
    "[org.tanzu.cfpulse]": DEBUG
    "[org.cloudfoundry]": DEBUG
    "[io.modelcontextprotocol]": DEBUG
