cf:
  apiHost: ${vcap.services.cf-client.credentials.apihost:${CF_APIHOST:}}
  username: ${vcap.services.cf-client.credentials.username:${CF_USERNAME:}}
  password: ${vcap.services.cf-client.credentials.password:${CF_PASSWORD:}}
  organization: ${vcap.services.cf-client.credentials.org:${CF_ORG}}
  space: ${vcap.services.cf-client.credentials.space:${CF_SPACE}}
